query characters($page: Int, $filter: FilterCharacter) {
  characters(page: $page, filter: $filter) {
    info {
      ...Info
    }
    results {
      id
      name
      status
      species
      gender
      type
      origin {
        name
      }
      location {
        name
      }
      image
    }
  }
}
