export enum APP_CONSTANTS {
  APP_NAME = 'RICK & MORTY',
  EPISODES = 'Episodes',
  CHARACTERS = 'Characters',
  LOCATIONS = 'Locations',
  ADD_EPISODE = 'Add new episode',
  ADD_CHARACTER = 'Add new character',
  ADD_LOCATION = 'Add new location',
  EDIT = 'Edit',
  DELETE = 'Delete',
  FILTER_BY_NAME = 'Filter by name',
  FILTER_BY_STATUS = 'Filter by status',
  FILTER_BY_SPECIES = 'Filter by species',
  FILTER_BY_TYPE = 'Filter by type',
  FILTER_BY_GENDER = 'Filter by gender',
  FILTER_BY_DIMENSION = 'Filter by dimension',
  FILTER_BY_EPISODE = 'Filter by episode',
}
